Repository Alfresco/alfresco-mobile-workspace-android, pull requests merged in 2022-03, with the labels that each got.

#86 Mobileapps-1090
  app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
Labels: PR: reviewed-approved

#87 Mobileapps-1097
  search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt
Labels: PR: reviewed-approved

#88 Mobileapps-1089
  app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
Labels: PR: reviewed-approved

#89 Mobileapps-1098
  app/src/main/AndroidManifest.xml
  listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
  listview/src/main/kotlin/com/alfresco/content/listview/ListViewRow.kt
Labels: PR: reviewed-approved

#92 Mobileapps 1083
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadExtensionFiles.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadFiles.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadMedia.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
  app/src/main/res/navigation/nav_bottom.xml
  auth/src/main/res/values/strings.xml
  browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewState.kt
  browse/src/main/kotlin/com/alfresco/content/browse/transfer/TransferFilesFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/transfer/TransferFilesViewModel.kt
  browse/src/main/res/values/strings.xml
  common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
  data/objectbox-models/default.json
  data/src/main/kotlin/com/alfresco/content/data/Entry.kt
  data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
  listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
  listview/src/main/res/drawable/ic_upload.xml
  listview/src/main/res/layout/fragment_list.xml
  listview/src/main/res/layout/fragment_transfer_files_list.xml
  listview/src/main/res/values/strings.xml
  search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt
  shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt
Labels: PR: reviewed-approved

#93 LOC-354 partial fix Localised files in ES (Spanish)
  actions/src/main/res/values-es/strings.xml
  app/src/main/res/values-es/strings.xml
  auth/src/main/res/values-es/strings.xml
  browse/src/main/res/values-es/strings.xml
  capture/src/main/res/values-es/strings.xml
  download/src/main/res/values-es/strings.xml
  listview/src/main/res/values-es/strings.xml
  search/src/main/res/values-es/strings.xml
  shareextension/src/main/res/values-es/strings.xml
  viewer-media/src/main/res/values-es/strings.xml
  viewer-pdf/src/main/res/values-es/strings.xml
  viewer/src/main/res/values-es/strings.xml
Labels: PR: reviewed-approved

#94 LOC-354 partial fix All 5 languages (DE, NL, IT, ES, FR) localized in…
  actions/src/main/res/values-de/strings.xml
  actions/src/main/res/values-fr/strings.xml
  actions/src/main/res/values-it/strings.xml
  actions/src/main/res/values-nl/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  auth/src/main/res/values-de/strings.xml
  auth/src/main/res/values-es/strings.xml
  auth/src/main/res/values-fr/strings.xml
  auth/src/main/res/values-it/strings.xml
  auth/src/main/res/values-nl/strings.xml
  browse/src/main/res/values-de/strings.xml
  browse/src/main/res/values-fr/strings.xml
  browse/src/main/res/values-it/strings.xml
  browse/src/main/res/values-nl/strings.xml
  capture/src/main/res/values-de/strings.xml
  capture/src/main/res/values-es/strings.xml
  capture/src/main/res/values-fr/strings.xml
  capture/src/main/res/values-it/strings.xml
  capture/src/main/res/values-nl/strings.xml
  common/src/main/res/values-de/strings.xml
  common/src/main/res/values-es/strings.xml
  common/src/main/res/values-fr/strings.xml
  common/src/main/res/values-it/strings.xml
  common/src/main/res/values-nl/strings.xml
  download/src/main/res/values-de/strings.xml
  download/src/main/res/values-fr/strings.xml
  download/src/main/res/values-it/strings.xml
  download/src/main/res/values-nl/strings.xml
  listview/src/main/res/values-de/strings.xml
  listview/src/main/res/values-fr/strings.xml
  listview/src/main/res/values-it/strings.xml
  listview/src/main/res/values-nl/strings.xml
  search/src/main/res/values-de/strings.xml
  search/src/main/res/values-fr/strings.xml
  search/src/main/res/values-it/strings.xml
  search/src/main/res/values-nl/strings.xml
  shareextension/src/main/res/values-de/strings.xml
  shareextension/src/main/res/values-fr/strings.xml
  shareextension/src/main/res/values-it/strings.xml
  shareextension/src/main/res/values-nl/strings.xml
  viewer-media/src/main/res/values-de/strings.xml
  viewer-media/src/main/res/values-fr/strings.xml
  viewer-media/src/main/res/values-it/strings.xml
  viewer-media/src/main/res/values-nl/strings.xml
  viewer-pdf/src/main/res/values-de/strings.xml
  viewer-pdf/src/main/res/values-fr/strings.xml
  viewer-pdf/src/main/res/values-it/strings.xml
  viewer-pdf/src/main/res/values-nl/strings.xml
  viewer/src/main/res/values-de/strings.xml
  viewer/src/main/res/values-fr/strings.xml
  viewer/src/main/res/values-it/strings.xml
  viewer/src/main/res/values-nl/strings.xml
Labels: PR: unreviewed

#95 Mobileapps 1083
  actions/src/main/kotlin/com/alfresco/content/actions/ActionCaptureMedia.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionPermission.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadExtensionFiles.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadFiles.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadMedia.kt
  app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/transfer/TransferFilesFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/transfer/TransferFilesViewModel.kt
  capture/src/main/kotlin/com/alfresco/capture/CaptureHelperFragment.kt
  capture/src/main/kotlin/com/alfresco/capture/CapturePhotoResultContract.kt
  data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/SyncService.kt
  data/src/main/kotlin/com/alfresco/content/data/UploadWorker.kt
  listview/src/main/res/drawable/ic_upload.xml
  listview/src/main/res/drawable/ic_upload_done.xml
  listview/src/main/res/layout/fragment_list.xml
  listview/src/main/res/layout/view_list_message.xml
  listview/src/main/res/values-de/strings.xml
  listview/src/main/res/values-es/strings.xml
  listview/src/main/res/values-fr/strings.xml
  listview/src/main/res/values-it/strings.xml
  listview/src/main/res/values-nl/strings.xml
  listview/src/main/res/values/strings.xml
  viewer-media/src/main/kotlin/com/alfresco/content/viewer/media/MediaViewerFragment.kt
Labels: PR: partially-approved

#96 localization_fix
  actions/src/main/res/values-it/strings.xml
  actions/src/main/res/values/strings.xml
  app/src/main/res/navigation/nav_bottom.xml
Labels: PR: reviewed-approved
