Repository Alfresco/alfresco-mobile-workspace-android, pull requests merged in 2022-09, with the labels that each got.

#160 LOC-384 - 3rd update to the UI in 5 languages
  browse/src/main/res/values-de/strings.xml
  browse/src/main/res/values-es/strings.xml
  browse/src/main/res/values-fr/strings.xml
  browse/src/main/res/values-it/strings.xml
  browse/src/main/res/values-nl/strings.xml
Labels: PR: reviewed-approved

#161 added download feature on preview screen for task attachments
  actions/src/main/kotlin/com/alfresco/content/actions/ActionOpenWith.kt
  browse/src/main/AndroidManifest.xml
  browse/src/main/kotlin/com/alfresco/content/browse/preview/LocalPreviewActivity.kt
  browse/src/main/kotlin/com/alfresco/content/browse/preview/LocalPreviewFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/preview/LocalPreviewViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/attachments/AttachedFilesFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
  browse/src/main/res/layout/activity_local_preview.xml
  browse/src/main/res/menu/menu_preview.xml
  data/objectbox-models/default.json
  data/src/main/kotlin/com/alfresco/content/data/Entry.kt
  mimetype/src/main/kotlin/com/alfresco/content/mimetype/MimeType.kt
Labels: PR: unreviewed

#162 preview crash
  browse/src/main/kotlin/com/alfresco/content/browse/preview/LocalPreviewFragment.kt
  data/objectbox-models/default.json
  data/objectbox-models/default.json.bak
Labels: PR: unreviewed

#164 Mobileapps 1422
  actions/src/main/kotlin/com/alfresco/content/actions/CreateTaskDialog.kt
  actions/src/main/res/layout/dialog_create_layout.xml
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/comments/CommentsFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/res/drawable/ic_completed_tick.xml
  browse/src/main/res/layout/fragment_task_detail.xml
  browse/src/main/res/layout/sheet_filter_create.xml
  browse/src/main/res/values/strings.xml
  common/src/main/kotlin/com/alfresco/content/ContextExt.kt
  component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/ComponentSheetExtension.kt
  component/src/main/java/com/alfresco/content/component/ComponentType.kt
  component/src/main/res/layout/sheet_component_filter.xml
  component/src/main/res/layout/view_single_input_text_component.xml
  component/src/main/res/layout/view_text_component.xml
  data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
  listview/src/main/kotlin/com/alfresco/content/listview/TextViewExt.kt
  listview/src/main/res/values/strings.xml
  search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
Labels: PR: reviewed-approved

#165 MOBILEAPPS-1449
  actions/src/main/kotlin/com/alfresco/content/actions/Action.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionCreateTask.kt
  actions/src/main/res/values/strings.xml
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewState.kt
  browse/src/main/res/drawable/ic_clear.xml
  browse/src/main/res/drawable/ic_edit.xml
  browse/src/main/res/layout/fragment_task_detail.xml
  browse/src/main/res/menu/menu_task_detail.xml
  browse/src/main/res/values-de/strings.xml
  browse/src/main/res/values-es/strings.xml
  browse/src/main/res/values-fr/strings.xml
  browse/src/main/res/values-it/strings.xml
  browse/src/main/res/values-nl/strings.xml
  browse/src/main/res/values/strings.xml
  component/src/main/java/com/alfresco/content/component/ComponentSheetExtension.kt
  component/src/main/res/layout/sheet_component_filter.xml
  component/src/main/res/layout/view_text_component.xml
  component/src/main/res/layout/view_title_description_component.xml
  data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  listview/src/main/kotlin/com/alfresco/content/listview/TextViewExt.kt
  listview/src/main/res/values-night/colors.xml
  listview/src/main/res/values/colors.xml
  theme/src/main/res/values/themes.xml
Labels: PR: reviewed-approved

#168 MOBILEAPPS-1404
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/comments/ListViewCommentRow.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  browse/src/main/res/layout/fragment_task_detail.xml
  common/src/main/kotlin/com/alfresco/content/ZoneDateTimeExt.kt
  component/src/main/java/com/alfresco/content/component/ComponentViewModel.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
Labels: PR: partially-approved

#167 Mobileapps 1455
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
Labels: PR: reviewed-approved

#169 Mobileapps 1410
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  build.gradle
  common/src/main/AndroidManifest.xml
  common/src/main/kotlin/com/alfresco/content/TaskPriority.kt
  common/src/main/kotlin/com/alfresco/content/common/TextViewExt.kt
  common/src/main/res/drawable/bg_priority_high.xml
  common/src/main/res/drawable/bg_priority_low.xml
  common/src/main/res/drawable/bg_priority_medium.xml
  common/src/main/res/drawable/bg_priority_reset.xml
  common/src/main/res/values-de/strings.xml
  common/src/main/res/values-es/strings.xml
  common/src/main/res/values-fr/strings.xml
  common/src/main/res/values-it/strings.xml
  common/src/main/res/values-night/colors.xml
  common/src/main/res/values-nl/strings.xml
  common/src/main/res/values/colors.xml
  common/src/main/res/values/strings.xml
  component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/ComponentSheetExtension.kt
  component/src/main/java/com/alfresco/content/component/ComponentType.kt
  component/src/main/java/com/alfresco/content/component/ComponentViewModel.kt
  component/src/main/res/layout/sheet_component_filter.xml
  component/src/main/res/layout/view_task_priority_component.xml
  data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
  listview/src/main/res/values-de/strings.xml
  listview/src/main/res/values-es/strings.xml
  listview/src/main/res/values-fr/strings.xml
  listview/src/main/res/values-it/strings.xml
  listview/src/main/res/values-night/colors.xml
  listview/src/main/res/values-nl/strings.xml
  listview/src/main/res/values/colors.xml
  listview/src/main/res/values/strings.xml
Labels: PR: reviewed-approved

#171 MOBILEAPPS-1400
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
Labels: PR: reviewed-approved

#170 MOBILEAPPS-1416
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/res/layout/fragment_task_detail.xml
  common/src/main/res/drawable/bg_user.xml
  common/src/main/res/values-night/colors.xml
  common/src/main/res/values/colors.xml
  component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/ComponentSheetExtension.kt
  component/src/main/java/com/alfresco/content/component/ListViewUserRow.kt
  component/src/main/java/com/alfresco/content/component/ParentComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentBuilder.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentState.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentViewModel.kt
  component/src/main/res/layout/sheet_component_search_user.xml
  component/src/main/res/layout/view_list_user_row.xml
  component/src/main/res/layout/view_task_priority_component.xml
  component/src/main/res/values-night/colors.xml
  component/src/main/res/values/colors.xml
  component/src/main/res/values/strings.xml
  data/src/main/kotlin/com/alfresco/content/data/ResponseUserList.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  listview/src/main/res/values-night/colors.xml
  listview/src/main/res/values/colors.xml
Labels: PR: reviewed-approved

#172 Mobileapps 1423
  app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
  app/src/main/java/com/alfresco/content/app/fragment/SettingsFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
  component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/ListViewUserRow.kt
  component/src/main/java/com/alfresco/content/component/ParentComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentBuilder.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentState.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentViewModel.kt
  component/src/main/res/layout/sheet_component_search_user.xml
  component/src/main/res/layout/view_list_user_row.xml
  component/src/main/res/values/strings.xml
  data/src/main/kotlin/com/alfresco/content/data/ResponseUserList.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/UserDetails.kt
Labels: PR: reviewed-approved
