Repository Alfresco/alfresco-mobile-workspace-android, pull requests merged in 2023-04, with the labels that each got.

#225 MOBILEAPPS-1727
  actions/src/main/kotlin/com/alfresco/content/actions/ActionStartProcess.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
  actions/src/main/res/values/strings.xml
  app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
  app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
  build.gradle
  data/src/main/kotlin/com/alfresco/content/data/Settings.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/payloads/SystemPropertiesEntry.kt
  listview/src/main/res/layout/fragment_process_list.xml
Labels: PR: partially-approved

#227 link content to processes
  actions/src/main/kotlin/com/alfresco/content/actions/ActionStartProcess.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsSheet.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsState.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsViewModel.kt
  actions/src/main/res/values/strings.xml
  data/objectbox-models/default.json
  data/src/main/kotlin/com/alfresco/content/data/Entry.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/payloads/LinkContentPayload.kt
Labels: PR: reviewed-approved

#228 MOBILEAPPS-1729
  actions/src/main/kotlin/com/alfresco/content/actions/ListRowProcessDefinitions.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsSheet.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsState.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsViewModel.kt
  actions/src/main/res/layout/view_process_definitions_list_row.xml
  app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
  app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
  data/objectbox-models/default.json.bak
  data/src/main/kotlin/com/alfresco/content/data/ProcessDefinitionDataEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/ResponseListProcessDefinitions.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
Labels: PR: partially-approved

#231 MOBILEAPPS-1791
  app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
Labels: PR: unreviewed

#232 update_variable
  app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
Labels: PR: unreviewed

#233 MOBILEAPPS-1802
  actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsSheet.kt
Labels: PR: partially-approved

#234 MOBILEAPPS-1730
  actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
  browse/src/main/AndroidManifest.xml
  browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/ProcessDetailActivity.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewState.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsSheet.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsState.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/res/layout/fragment_task_detail.xml
  browse/src/main/res/navigation/nav_task_paths.xml
  browse/src/main/res/values/strings.xml
  common/src/main/kotlin/com/alfresco/content/common/TextViewExt.kt
  common/src/main/res/values/strings.xml
  component/src/main/java/com/alfresco/content/component/ComponentSheetExtension.kt
  component/src/main/res/layout/view_title_description_component.xml
  data/src/main/kotlin/com/alfresco/content/data/AnalyticsRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/ProcessDefinitionDataEntry.kt
  listview/src/main/kotlin/com/alfresco/content/listview/EntryListener.kt
  listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
  listview/src/main/kotlin/com/alfresco/content/listview/TextViewExt.kt
  listview/src/main/kotlin/com/alfresco/content/listview/processes/ListRowProcessDefinitions.kt
  listview/src/main/kotlin/com/alfresco/content/listview/tasks/ListViewTaskRow.kt
  listview/src/main/res/layout/view_process_definitions_list_row.xml
Labels: PR: partially-approved

#236 Mobileapps-1732
  actions/src/main/kotlin/com/alfresco/content/actions/ActionCreateTask.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUpdateNameDescription.kt
  actions/src/main/kotlin/com/alfresco/content/actions/CreateTaskDialog.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ListRowProcessDefinitions.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewState.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsSheet.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsState.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/ComponentType.kt
  data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/ResponseListProcessDefinitions.kt
  data/src/main/kotlin/com/alfresco/content/data/RuntimeProcessDefinitionDataEntry.kt
  listview/src/main/kotlin/com/alfresco/content/listview/processes/ListRowProcessDefinitions.kt
Labels: PR: unreviewed

#237 Mobileapps 1731
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/comments/ListViewCommentRow.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  component/build.gradle
  component/src/main/java/com/alfresco/content/component/ComponentViewModel.kt
  component/src/main/java/com/alfresco/content/component/ListViewUserRow.kt
  component/src/main/java/com/alfresco/content/component/SearchUserComponentState.kt
  component/src/main/java/com/alfresco/content/component/SearchUserGroupComponentBuilder.kt
  component/src/main/java/com/alfresco/content/component/SearchUserGroupComponentSheet.kt
  component/src/main/java/com/alfresco/content/component/SearchUserGroupComponentSheetExtension.kt
  component/src/main/java/com/alfresco/content/component/SearchUserGroupComponentState.kt
  component/src/main/java/com/alfresco/content/component/SearchUserGroupComponentViewModel.kt
  component/src/main/res/layout/sheet_component_search_user.xml
  component/src/test/java/com/alfresco/content/app/component/ComponentViewModelTest.kt
  component/src/test/java/com/alfresco/content/app/component/SearchUserGroupComponentViewModelTest.kt
  data/src/main/kotlin/com/alfresco/content/data/CommentEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/Entry.kt
  data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/ResponseList.kt
  data/src/main/kotlin/com/alfresco/content/data/ResponseUserGroupList.kt
  data/src/main/kotlin/com/alfresco/content/data/ResponseUserList.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/UserDetails.kt
  data/src/main/kotlin/com/alfresco/content/data/UserGroupDetails.kt
Labels: PR: partially-approved

#238 fixed build crash
  app/build.gradle
  component/build.gradle
Labels: PR: unreviewed

#235 LOC-413 Fully updated UI ANDROID files in 5 languages including copyr…
  actions/src/main/res/values-de/strings.xml
  actions/src/main/res/values-es/strings.xml
  actions/src/main/res/values-fr/strings.xml
  actions/src/main/res/values-it/strings.xml
  actions/src/main/res/values-nl/strings.xml
  auth/src/main/res/values-de/strings.xml
  auth/src/main/res/values-es/strings.xml
  auth/src/main/res/values-fr/strings.xml
  auth/src/main/res/values-it/strings.xml
  auth/src/main/res/values-nl/strings.xml
  browse/src/main/res/values-de/strings.xml
  browse/src/main/res/values-es/strings.xml
  browse/src/main/res/values-fr/strings.xml
  browse/src/main/res/values-it/strings.xml
  browse/src/main/res/values-nl/strings.xml
  common/src/main/res/values-de/strings.xml
  common/src/main/res/values-es/strings.xml
  common/src/main/res/values-fr/strings.xml
  common/src/main/res/values-it/strings.xml
  common/src/main/res/values-nl/strings.xml
  component/src/main/res/values-de/strings.xml
  component/src/main/res/values-es/strings.xml
  component/src/main/res/values-fr/strings.xml
  component/src/main/res/values-it/strings.xml
  component/src/main/res/values-nl/strings.xml
  search/src/main/res/values-es/strings.xml
Labels: PR: unreviewed

#239 MOBILEAPPS-1735
  actions/src/main/kotlin/com/alfresco/content/actions/Action.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionCaptureMedia.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionOpenWith.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadFiles.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadMedia.kt
  actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
  actions/src/main/kotlin/com/alfresco/content/actions/CreateActionsSheet.kt
  app/build.gradle
  app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
  browse/src/main/assets/task.filters.json
  browse/src/main/kotlin/com/alfresco/content/browse/offline/OfflineFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/preview/LocalPreviewFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/attachments/ProcessAttachedFilesFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewState.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsSheet.kt
  browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsViewModel.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/BaseDetailFragment.kt
  browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
  browse/src/main/res/navigation/nav_task_paths.xml
  capture/src/main/kotlin/com/alfresco/capture/CaptureModeSelectorView.kt
  component/build.gradle
  data/objectbox-models/default.json
  data/objectbox-models/default.json.bak
  data/src/main/kotlin/com/alfresco/content/data/AnalyticsRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/Entry.kt
  data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
  data/src/main/kotlin/com/alfresco/content/data/ResponseContents.kt
  data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
  data/src/main/kotlin/com/alfresco/content/data/UploadWorker.kt
  search/src/main/res/values-es/strings.xml
  viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerFragment.kt
Labels: PR: unreviewed
